In [50]:
#Import libraries
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [51]:
csv = 'mergedworms.csv'# Read the CSV file
data = pd.read_csv(csv)

np.random.seed(4)

In [52]:
print(f"Shape {data.shape}")
# Print all column headers
print(data.columns)

Shape (3575, 17)
Index(['id', 'group', 'average_speed', 'average_distance_per_frame',
       'maximal_distance_traveled', 'average_change_in_pixels',
       'average_angular_speed', 'distance_travaled', 'distance_travaled.1',
       'average_change_speed', 'time_elapsed_(hours)', 'std_speed', 'std/mean',
       'roaming_fraction', 'lifespan', 'drugged', 'worm_id'],
      dtype='object')


In [53]:
# Count occurrences of values in the 'worm_id' column
value_counts = data['worm_id'].value_counts()

# Print the counts
# print(value_counts.sort_values(axis=0, ascending=False))

In [54]:
value_counts.shape

(48,)

In [55]:
from training_functions import *
#splits data by worm id into train and test, 80/20 test train split
train_data, test_data = split_by_worm_id(data, test_size=0.2)
X_train, y_train, X_test, y_test = train_test_x_and_y(train_data, test_data)

In [56]:
# test_value_counts = test_data['worm_id'].value_counts()
# train_value_counts = train_data['worm_id'].value_counts()

In [57]:
#Check to make sure it works
# train_value_counts.shape

In [58]:
from training_functions import *
#splits data by worm id into train and test, 80/20 test train split
train_data, test_data = split_by_worm_id(data, test_size=0.2)
X_train, y_train, X_test, y_test = train_test_x_and_y(train_data, test_data)


In [59]:
#sample imputing (NEED TO IMPROVE) -- ONLY TEMPORARY
if np.isnan(X_train).any().any() or np.isnan(X_test).any().any():
  # Impute missing values with the median
  imputer = SimpleImputer(strategy='median')
  X_train = imputer.fit_transform(X_train)
  X_test = imputer.fit_transform(X_test)

# # Check for NaN values in X_train and y_train
print("NaNs in X_train:", np.isnan(X_train).any())
print("NaNs in y_train:", np.isnan(y_train).any())

# Check for infinity values in X_train
print("Infinity values in X_train:", np.isinf(X_train).any())

NaNs in X_train: False
NaNs in y_train: False
Infinity values in X_train: False


# Models

## Logistic Regression

In [60]:

model = LogisticRegression(penalty='l2', max_iter=700, multi_class='multinomial')
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5994318181818182
Precision: 0.6900028217628162
Recall: 0.5994318181818182
F1-score: 0.5219493766704607
Confusion Matrix:
 [[194  29   3]
 [ 32 220   0]
 [218   0   8]]


## Decision Tree Classifier

In [61]:
# Create and train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8806818181818182
Precision: 0.9130131964809384
Recall: 0.8806818181818182
F1-score: 0.8764135412365053
Confusion Matrix:
 [[226   0   0]
 [  0 252   0]
 [ 84   0 142]]


## Random Forest Classifier

In [62]:
# Create and train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.8821022727272727
Precision: 0.9137705942924389
Recall: 0.8821022727272727
F1-score: 0.8779881099575652
Confusion Matrix:
 [[226   0   0]
 [  0 252   0]
 [ 83   0 143]]


## Support Vector Machine

In [63]:
# Create and train the model
model = SVC()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.3409090909090909
Precision: 0.4631011198945982
Recall: 0.3409090909090909
F1-score: 0.1960880205177493
Confusion Matrix:
 [[226   0   0]
 [238  14   0]
 [226   0   0]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Naive Bayes

In [64]:
# Create and train the model
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.6818181818181818
Precision: 0.7177367858632193
Recall: 0.6818181818181818
F1-score: 0.5950130203308962
Confusion Matrix:
 [[220   2   4]
 [  0 250   2]
 [216   0  10]]


In [65]:
print("y_train\n", y_train.value_counts())
print("y_test\n", y_test.value_counts())

y_train
 0    1521
1     720
2     630
Name: drugged, dtype: int64
y_test
 1    252
2    226
0    226
Name: drugged, dtype: int64
