In [1]:
#Import libraries
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.impute import SimpleImputer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [2]:
csv = 'mergedworms.csv'# Read the CSV file
data = pd.read_csv(csv)

np.random.seed(42)

In [3]:
print(f"Shape {data.shape}")
# Print all column headers
print(data.columns)

Shape (3575, 17)
Index(['id', 'group', 'average_speed', 'average_distance_per_frame',
       'maximal_distance_traveled', 'average_change_in_pixels',
       'average_angular_speed', 'total_distance_traveled',
       'distance_traveled_bin', 'average_acceleration', 'time_elapsed_(hours)',
       'std_speed', 'std/mean', 'roaming_fraction', 'lifespan', 'drugged',
       'worm_id'],
      dtype='object')


In [4]:
# Count occurrences of values in the 'worm_id' column
value_counts = data['worm_id'].value_counts()

# Print the counts
print(value_counts.sort_values(axis=0, ascending=False))

47    84
3     84
37    84
27    84
25    84
43    84
2     84
11    84
9     84
7     84
5     84
44    84
32    84
24    84
12    84
10    84
8     84
4     84
19    84
45    83
46    83
42    83
41    82
23    80
17    72
30    72
6     72
26    72
28    72
34    72
21    72
40    72
31    72
14    71
15    70
29    70
20    67
18    60
13    60
39    60
1     60
48    60
16    60
35    60
38    60
33    59
36    55
22    48
Name: worm_id, dtype: int64


In [5]:
value_counts.shape

(48,)

In [6]:
from training_functions import *
#splits data by worm id into train and test, 80/20 test train split
train_data, test_data = split_by_worm_id(data, test_size=0.2)
X_train, y_train, X_test, y_test = train_test_x_and_y(train_data, test_data)

In [7]:
# test_value_counts = test_data['worm_id'].value_counts()
# train_value_counts = train_data['worm_id'].value_counts()

In [8]:
#Check to make sure it works
# train_value_counts.shape

In [9]:
from training_functions import *
#splits data by worm id into train and test, 80/20 test train split
train_data, test_data = split_by_worm_id(data, test_size=0.2)


# train_data.loc(train_data['std_speed'] == None)

X_train, y_train, X_test, y_test = train_test_x_and_y(train_data, test_data)


In [10]:
# # Check for NaN values in X_train and y_train
print("NaNs in X_train:", np.isnan(X_train).any())
print("NaNs in y_train:", np.isnan(y_train).any())

# Check for infinity values in X_train
print("Infinity values in X_train:", np.isinf(X_train).any())

# sample imputing (NEED TO IMPROVE) -- ONLY TEMPORARY
if np.isnan(X_train).any().any() or np.isnan(X_test).any().any():
  # Impute missing values with the median
  imputer = SimpleImputer(strategy='median')
  X_train = imputer.fit_transform(X_train)
  X_test = imputer.fit_transform(X_test)



NaNs in X_train: id                          False
average_speed               False
average_change_in_pixels    False
average_angular_speed       False
total_distance_traveled     False
distance_traveled_bin       False
time_elapsed_(hours)        False
std_speed                    True
std/mean                     True
roaming_fraction            False
lifespan                    False
dtype: bool
NaNs in y_train: False
Infinity values in X_train: id                          False
average_speed               False
average_change_in_pixels    False
average_angular_speed       False
total_distance_traveled     False
distance_traveled_bin       False
time_elapsed_(hours)        False
std_speed                   False
std/mean                    False
roaming_fraction            False
lifespan                    False
dtype: bool


# Models

## Logistic Regression

In [11]:

model = LogisticRegression(penalty='l2', max_iter=700, multi_class='multinomial')
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7285714285714285
Precision: 0.6876481345115366
Recall: 0.7285714285714285
F1-score: 0.674372515153102
Confusion Matrix:
 [[312   0  17]
 [ 37 191   0]
 [136   0   7]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


## Decision Tree Classifier

In [12]:
# Create and train the model
model = DecisionTreeClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0
Confusion Matrix:
 [[329   0   0]
 [  0 228   0]
 [  0   0 143]]


## Random Forest Classifier

In [13]:
# Create and train the model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7071428571428572
Precision: 0.732859649122807
Recall: 0.7071428571428572
F1-score: 0.7165462165462166
Confusion Matrix:
 [[203   0 126]
 [  0 228   0]
 [ 79   0  64]]


## Support Vector Machine

In [14]:
# Create and train the model
model = SVC()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.6371428571428571
Precision: 0.590945846606224
Recall: 0.6371428571428571
F1-score: 0.5600201318513676
Confusion Matrix:
 [[329   0   0]
 [111 117   0]
 [143   0   0]]


/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Naive Bayes

In [15]:
# Create and train the model
model = GaussianNB()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7771428571428571
Precision: 0.6809778376759509
Recall: 0.7771428571428571
F1-score: 0.7006035226392082
Confusion Matrix:
 [[326   0   3]
 [  9 217   2]
 [142   0   1]]


In [16]:
print("y_train\n", y_train.value_counts())
print("y_test\n", y_test.value_counts())

y_train
 0    1418
1     744
2     713
Name: drugged, dtype: int64
y_test
 0    329
1    228
2    143
Name: drugged, dtype: int64


## LSTM

In [17]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [18]:
# Create the LSTM model
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(LSTM(units=50))
model.add(Dense(1))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
90/90 [==============================] - 4s 7ms/step - loss: 0.6959
Epoch 2/10
90/90 [==============================] - 1s 7ms/step - loss: 0.6827
Epoch 3/10
90/90 [==============================] - 1s 7ms/step - loss: 0.6785
Epoch 4/10
90/90 [==============================] - 1s 7ms/step - loss: 0.6636
Epoch 5/10
90/90 [==============================] - 1s 7ms/step - loss: 0.6446
Epoch 6/10
90/90 [==============================] - 1s 7ms/step - loss: 0.5986
Epoch 7/10
90/90 [==============================] - 1s 8ms/step - loss: 0.5644
Epoch 8/10
90/90 [==============================] - 1s 7ms/step - loss: 0.5512
Epoch 9/10
90/90 [==============================] - 1s 7ms/step - loss: 0.5272
Epoch 10/10
90/90 [==============================] - 1s 7ms/step - loss: 0.5165


In [19]:
y_pred = model.predict(X_test)
# Assuming y_pred contains predicted probabilities for each class
thresholds = [0.5, 1.5]
y_pred_labels = np.zeros_like(y_pred)
y_pred_labels[y_pred < thresholds[0]] = 0
y_pred_labels[(y_pred >= thresholds[0]) & (y_pred < thresholds[1])] = 1
y_pred_labels[y_pred >= thresholds[1]] = 2
y_pred_labels = y_pred_labels.astype(int)

# Assuming y_test contains the true labels
accuracy = accuracy_score(y_test, y_pred_labels)
precision = precision_score(y_test, y_pred_labels, average='weighted')
recall = recall_score(y_test, y_pred_labels, average='weighted')
f1 = f1_score(y_test, y_pred_labels, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred_labels)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-score:", f1)
print("Confusion Matrix:\n", conf_matrix)

22/22 [==============================] - 1s 3ms/step
Accuracy: 0.33
Precision: 0.276780918384692
Recall: 0.33
F1-score: 0.27835089558084497
Confusion Matrix:
 [[ 83 245   1]
 [ 80 148   0]
 [ 59  84   0]]


In [20]:
np.corrcoef(train_data)

for x in train_data.columns:
    for z in train_data.columns:
        if (np.corrcoef(train_data[x], y=train_data[z]))[0][1] > 0.75 and x != z:
            print(x,z)
            print(np.corrcoef(train_data[x], y=train_data[z]))

#speed and distance are the same, drop 1
#maximal distance travelled and distance 1:1

In [21]:
train_data.head

<bound method NDFrame.head of         id  average_speed  average_change_in_pixels  average_angular_speed  \
60      60       0.937451                 -0.012129               1.365049   
61      61       1.634150                 -0.048443               1.108255   
62      62       0.386344                  0.015686               1.158382   
63      63       0.683949                  0.019406               1.526128   
64      64       0.340302                 -0.003337               1.688612   
...    ...            ...                       ...                    ...   
3570  3570       0.043177                  0.000000               1.505476   
3571  3571       0.071912                  0.001112               1.495528   
3572  3572       0.039286                 -0.004449               1.556866   
3573  3573       0.039381                  0.002225               1.475976   
3574  3574       0.046272                  0.033557               1.634871   

      total_distance_traveled  di